const clothingData = [
  { number: 1, name: "Technology in Clothing", style: "Tech", quality: "Premium", price: "Medium", audience: "Business" },
  { number: 2, name: "Retro Return", style: "Retro", quality: "Premium", price: "Medium", audience: "Teenagers" },
  { number: 3, name: "Rebellion Against Tradition", style: "Rebel", quality: "Budget", price: "Affordable", audience: "Teenagers" },
  { number: 4, name: "The return of grunge", style: "Rebel", quality: "Medium", price: "Medium", audience: "Teenagers" },
  { number: 5, name: "The glamorous 2000s", style: "Bright", quality: "Premium", price: "Medium", audience: "Teenagers" },
  { number: 6, name: "Street Comfort", style: "Streetwear", quality: "Medium", price: "Affordable", audience: "Teenagers" },
  { number: 7, name: "Business Chic", style: "Business", quality: "Premium", price: "High", audience: "Teenagers" },
  { number: 8, name: "Freedom Festival", style: "Modern", quality: "Medium", price: "Medium", audience: "Teenagers" },
  { number: 9, name: "Sports as a lifestyle", style: "Streetwear", quality: "Premium", price: "Medium", audience: "Middle class" },
  { number: 10, name: "Digital Age", style: "Tech", quality: "Premium", price: "High", audience: "Premium" },
  { number: 11, name: "Minimalism in fashion", style: "Modern", quality: "Premium", price: "High", audience: "Premium" },
  { number: 12, name: "The return of grunge", style: "Rebel", quality: "Medium", price: "Affordable", audience: "Teenagers" },
  { number: 13, name: "Elite Comfort", style: "Modern", quality: "Premium", price: "High", audience: "Premium" },
  { number: 14, name: "Rock 'n' Roll Style", style: "Rebel", quality: "Budget", price: "Affordable", audience: "Teenagers" },
  { number: 15, name: "Luxury Suits", style: "Business", quality: "Premium", price: "High", audience: "Business" },
  { number: 16, name: "Urban Travelers", style: "Modern", quality: "Medium", price: "Medium", audience: "Middle" },
  { number: 17, name: "Beach Season", style: "Modern", quality: "Premium", price: "Affordable", audience: "Teenagers" },
  { number: 18, name: "Militaria Revival", style: "Rebel", quality: "Medium", price: "Medium", audience: "Middle" },
  { number: 19, name: "Cyberpunk Fashion", style: "Tech", quality: "Premium", price: "High", audience: "Teenagers" },
  { number: 20, name: "Romantic Style", style: "Modern", quality: "Premium", price: "High", audience: "Middle" },
  { number: 21, name: "Gangster chic", style: "Retro", quality: "Premium", price: "High", audience: "Premium" },
  { number: 22, name: "Second Life", style: "Modern", quality: "Medium", price: "Medium", audience: "Mass" },
  { number: 23, name: "Total chaos", style: "Rebel", quality: "Budget", price: "Affordable", audience: "Teenagers" },
  { number: 24, name: "Gothic Fashion", style: "Rebel", quality: "Medium", price: "High", audience: "Teenagers" },
  { number: 25, name: "Timeless Classic", style: "Business", quality: "Premium", price: "High", audience: "Business" },
  { number: 26, name: "Street Artist", style: "Street", quality: "Medium", price: "Medium", audience: "Teenagers" },
  { number: 27, name: "Winter coziness", style: "Modern", quality: "Premium", price: "Medium", audience: "Middle" },
  { number: 28, name: "Safari style", style: "Modern", quality: "Medium", price: "Medium", audience: "Middle" },
  { number: 29, name: "Cybersport Fashion", style: "Tech", quality: "Premium", price: "Medium", audience: "Teenagers" },
  { number: 30, name: "Unisex Fashion", style: "Modern", quality: "Medium", price: "Medium", audience: "Mass" },
  { number: 31, name: "New Elegance", style: "Modern", quality: "Premium", price: "High", audience: "Business" },
  { number: 32, name: "Sport-luxe", style: "Modern", quality: "Premium", price: "Medium", audience: "Middle" },
  { number: 33, name: "Futuristic Fashion", style: "Tech", quality: "Premium", price: "High", audience: "Premium" },
  { number: 34, name: "Business Casual", style: "Business", quality: "Premium", price: "Medium", audience: "Business" },
  { number: 35, name: "Youth Rebellion", style: "Bright", quality: "Medium", price: "Affordable", audience: "Teenagers" },
  { number: 36, name: "Summer Festival Style", style: "Bright", quality: "Medium", price: "Medium", audience: "Teenagers" },
  { number: 37, name: "Urban Dynamics", style: "Modern", quality: "Medium", price: "Medium", audience: "Middle" },
  { number: 38, name: "Glamorous Evening", style: "Glamor", quality: "Premium", price: "High", audience: "Premium" },
  { number: 39, name: "Retro Boom", style: "Retro", quality: "Medium", price: "Medium", audience: "Mass" },
  { number: 40, name: "Sporty Elegance", style: "Street", quality: "Premium", price: "Medium", audience: "Middle" },
  { number: 41, name: "Free street style", style: "Street", quality: "Medium", price: "Medium", audience: "Mass" },
  { number: 42, name: "Glamorous classic", style: "Glamor", quality: "Premium", price: "High", audience: "Premium" },
  { number: 43, name: "Evening Business chic", style: "Glamor", quality: "Premium", price: "High", audience: "Premium" },
  { number: 44, name: "Business chic", style: "Business", quality: "Premium", price: "High", audience: "Business" },
  { number: 45, name: "Rebellion against rules", style: "Rebel", quality: "Medium", price: "Affordable", audience: "Teenagers" },
  { number: 46, name: "Elite comfort", style: "Modern", quality: "Premium", price: "High", audience: "Premium" },
  { number: 47, name: "Urban adaptation", style: "Modern", quality: "Medium", price: "Medium", audience: "Middle" },
  { number: 48, name: "Unique design solutions", style: "Modern", quality: "Premium", price: "Exclusive", audience: "Premium" },
  { number: 49, name: "A new look at the classics", style: "Modern", quality: "Medium", price: "Medium", audience: "Business" },
  { number: 50, name: "Urban comfort", style: "Modern", quality: "Medium", price: "Medium", audience: "Business" },
  { number: 51, name: "Street Sport Chic", style: "Street", quality: "Medium", price: "Medium", audience: "Teenagers" },
  { number: 52, name: "Glamor of the 2000s", style: "Glamor", quality: "Medium", price: "Affordable", audience: "Teenagers" },
  { number: 53, name: "Brutal Fashion", style: "Rebel", quality: "Medium", price: "Affordable", audience: "Teenagers" },
  { number: 54, name: "Social elegance", style: "Glamor", quality: "Premium", price: "High", audience: "Premium" },
  { number: 55, name: "Urban cyberpunk", style: "Tech", quality: "Medium", price: "Medium", audience: "Middle" },
  { number: 56, name: "Travel Fashion", style: "Modern", quality: "Medium", price: "Medium", audience" "Middle" },
  { number: 57, name: "Hipster style", style: "Retro", quality: "Medium", price: "Medium", audience" "Middle" },
  { number: 58, name: "Smart Casual", style: "Business", quality: "Premium", price: "High", audience" "Business" },
  { number: 59, name: "Street Anarchy", style: "Street", quality: "Medium", price: "Affordable", audience" "Teenagers" },
  { number: 60, name: "Business style of the future", style: "Business", quality: "Premium", price: "High", audience" "Business" },
